trigger: none
pr:
  branches:
    include:
    - '*'
  paths:
    include:
      - 'src/core/plugin/luapi_application.h'

stages:
- stage: 'Build_Test_Stage'
  jobs:
  - job: 'Build_Test'
    pool:
      vmImage: 'ubuntu-20.04'
    displayName: 'Test if lua definitions file is up-to-date'
    steps:
    - checkout: self
    - bash: |
        sudo apt-get update
        sudo apt-get install python3
      displayName: 'Install python3'
    - bash: |
        echo $(git status)
        echo "generate the file fresh"
        python3 scripts/lua_def_file.py
        # check if it matches the one present in the repository
        git diff --exit-code src/core/plugin/luapi_application.def.lua  && { echo "Success: changes are compatible with clang-format-$VERSION"; exit 0; }

        # Failure: None of the allowed clang-format versions validated the changes
        echo "Error: generated lua definitions file does not match the present one"
        exit 1
      displayName: 'Generate lua definitions file'
